Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.10"

  config.vm.provider :virtualbox do |v|
    v.gui = true
    v.memory = 6000
    v.cpus = 4
  end

  #SSH forwarded port
  config.vm.network "forwarded_port", guest: 22, host:2222, id: "ssh", auto_correct: true
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"

  # Use network bridge
  config.vm.network "public_network",    use_dhcp_assigned_default_route: true
  #config.vm.network "public_network", bridge: "en1: Wi-Fi (AirPort)"
end
