---
name: CI - Build
on:
  push:
    branches:
      - "main"
jobs:
  test:
    name: Unit Tets
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x, 1.18.x, 1.19.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Unit Test
        run: go test ./... -v -coverprofile cover.out
      - name: Code Coverage
        run: go tool cover -func ./cover.out | grep total | awk '{print $3}'
